all: program1 program5 program10 program_opt

program1: main1.cpp
	g++ -o program1 main1.cpp

program5: main5.cpp
	g++ -o program5 main5.cpp

program10: main5.cpp
	g++ -o program10 main10.cpp

program_opt: main5.cpp
	g++ -o program_opt main_opt.cpp